require: rubocop-rspec

Style/BlockDelimiters:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 150

#Metrics/LineLength:
#  Max: 180

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

RSpec/DescribedClass:
  Enabled: false
